theme: jekyll-theme-minimal
title: 
description: Do you want to discover more?  Choose your section here !
show_downloads: True
navigation:
  - title: Home ğŸ¡
    url: /
  - title: From creation to reaction ğŸ¨ â¡ï¸ ğŸ’¡
    description: Understanding Youtubeâ€™s content dynamics
    url: cluster
  - title:  Uncovering the patterns of the  power players of youtube ğŸ” ğŸ“Š ğŸ¥
    url: newsandpolitics
  - title: A world of similarities  ğŸŒ ğŸ”— ğŸ¤
    description: Uncovering shared viewing patterns ğŸ‘ï¸â€ğŸ—¨ï¸ ğŸ“ˆ
    url: bubbles
  - title:  The keywords beyond the curtain ğŸ”‘ ğŸ­ ğŸ•µï¸â€â™‚ï¸
    description: Unveiling connections in shared videos. 
    url: description
