theme: jekyll-theme-minimal
title: 
description: Do you want to discover more?  Choose your section here !
show_downloads: True
navigation:
  - title: Home ğŸ¡
    url: /
  - title: From creation to reaction ğŸ¨ â¡ï¸ ğŸ’¡
    description: Understanding Youtubeâ€™s content dynamics
    url: cluster
  - title:  Uncovering the patterns of the  power players of youtube ğŸ” ğŸ“Š ğŸ¥
    url: newsandpolitics
  - title: Uncovering shared commenting patterns ğŸ‘ï¸â€ğŸ—¨ï¸ ğŸ“ˆ
    url: bubbles
  - title:  Peering Into the Bubbles ğŸ«§ğŸ‘€
    description: Exploring Content and Source Diversity
    url: description
